added symlink execution script, working on while getopts

diff --git a/project1/config_script b/project1/config_script
--- a/project1/config_script
+++ b/project1/config_script
@@ -1,6 +1,11 @@
 #!/usr/bin/env bash
 
-# check for pacakge installer script and execute it
+while getopts ":hpsx" opt;
+do
+  case $opt in
+    h)
+
+# check for package installer script and execute it
 if [[ -x ./package_installer ]];
 then
   echo "running package installer script"
@@ -10,6 +15,17 @@ else
   exit 1
 fi
 
-#
-#if [[ -x ./config_symlink ]];
-#then echo "Running symlink creation script
+
+
+#check symlink script and execute it
+#then echo "Running symlink creation script"
+if [[ -x ./symlink_script ]];
+then
+  echo "Running symlink creation script"
+  ./config_symlink
+else
+  echo "symlink_script not found or not executable"
+  exit 1
+fi
+
+echo "Configuration setup complete"
